// Autogenerated by Dirpcgen (2.3.4)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package idl

import "fmt"

// Attributes:
//  - Errno
//  - Errmsg
type Response struct {
	Errno  int32  `thrift:"errno,1,required" json:"errno"`
	Errmsg string `thrift:"errmsg,2,required" json:"errmsg"`
}

func NewResponse() *Response {
	return &Response{}
}

func (r *Response) New() *Response {
	return &Response{}
}

func (p *Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Response(%+v)", *p)
}

// Attributes:
//  - Online
//  - Test
type DiffBinaryReq struct {
	Online string `thrift:"online,1,required" json:"online"`
	Test   string `thrift:"test,2,required" json:"test"`
}

func NewDiffBinaryReq() *DiffBinaryReq {
	return &DiffBinaryReq{}
}

func (r *DiffBinaryReq) New() *DiffBinaryReq {
	return &DiffBinaryReq{}
}

func (p *DiffBinaryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DiffBinaryReq(%+v)", *p)
}

// Attributes:
//  - Diff
//  - Errmsg
type DiffBinaryResp struct {
	Diff   string `thrift:"diff,1,required" json:"diff"`
	Errmsg string `thrift:"errmsg,2,required" json:"errmsg"`
}

func NewDiffBinaryResp() *DiffBinaryResp {
	return &DiffBinaryResp{}
}

func (r *DiffBinaryResp) New() *DiffBinaryResp {
	return &DiffBinaryResp{}
}

func (p *DiffBinaryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DiffBinaryResp(%+v)", *p)
}
