// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	agent.proto

It has these top-level messages:
	RecordReq
	RecordRsp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RecordReq struct {
	EsData string `protobuf:"bytes,1,opt,name=esData" json:"esData,omitempty"`
}

func (m *RecordReq) Reset()                    { *m = RecordReq{} }
func (m *RecordReq) String() string            { return proto1.CompactTextString(m) }
func (*RecordReq) ProtoMessage()               {}
func (*RecordReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RecordReq) GetEsData() string {
	if m != nil {
		return m.EsData
	}
	return ""
}

type RecordRsp struct {
	Errno  int32  `protobuf:"varint,1,opt,name=errno" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Data   string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *RecordRsp) Reset()                    { *m = RecordRsp{} }
func (m *RecordRsp) String() string            { return proto1.CompactTextString(m) }
func (*RecordRsp) ProtoMessage()               {}
func (*RecordRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RecordRsp) GetErrno() int32 {
	if m != nil {
		return m.Errno
	}
	return 0
}

func (m *RecordRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *RecordRsp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto1.RegisterType((*RecordReq)(nil), "proto.RecordReq")
	proto1.RegisterType((*RecordRsp)(nil), "proto.RecordRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Agent service

type AgentClient interface {
	Record(ctx context.Context, in *RecordReq, opts ...grpc.CallOption) (*RecordRsp, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Record(ctx context.Context, in *RecordReq, opts ...grpc.CallOption) (*RecordRsp, error) {
	out := new(RecordRsp)
	err := grpc.Invoke(ctx, "/proto.Agent/Record", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agent service

type AgentServer interface {
	Record(context.Context, *RecordReq) (*RecordRsp, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Agent/Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Record(ctx, req.(*RecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Record",
			Handler:    _Agent_Record_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}

func init() { proto1.RegisterFile("agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xca, 0x5c, 0x9c, 0x41,
	0xa9, 0xc9, 0xf9, 0x45, 0x29, 0x41, 0xa9, 0x85, 0x42, 0x62, 0x5c, 0x6c, 0xa9, 0xc5, 0x2e, 0x89,
	0x25, 0x89, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x92, 0x2f, 0x5c, 0x51, 0x71,
	0x81, 0x90, 0x08, 0x17, 0x6b, 0x6a, 0x51, 0x51, 0x5e, 0x3e, 0x58, 0x0d, 0x6b, 0x10, 0x84, 0x03,
	0xd6, 0x5a, 0x54, 0x94, 0x5b, 0x9c, 0x2e, 0xc1, 0x04, 0xd5, 0x0a, 0xe6, 0x09, 0x09, 0x71, 0xb1,
	0xa4, 0x80, 0x0c, 0x64, 0x06, 0x8b, 0x82, 0xd9, 0x46, 0xe6, 0x5c, 0xac, 0x8e, 0x20, 0x97, 0x08,
	0xe9, 0x71, 0xb1, 0x41, 0xcc, 0x15, 0x12, 0x80, 0xb8, 0x4a, 0x0f, 0xee, 0x16, 0x29, 0x34, 0x91,
	0xe2, 0x02, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x90, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x3c,
	0x9a, 0x46, 0xc9, 0x00, 0x00, 0x00,
}
