
[http]
http_addr = ":9003"      # Listen ip:port, http server地址
handlerTimeout = 1000    # Handler timeout(ms), default 5000
readTimeout = 1000       # Recieve http request timeout(ms), including the body
writeTimeout = 1000      # Recieve http body and response timeout(ms)
idleTimeout = 5000       # Keep-alive timeout(ms)

[log]
filename = "log/recorder.log.%Y%m%d%H"
linkname = "log/recorder.log"
maxHourAge    = 4 # 默认日志保留4小时
maxHourRotate = 1 # 默认日志按小时切分

[es_url]
# 确保录制机器可以访问，check：`curl http://127.0.0.1:9002/xxx/recorder_index/_search`能写入数据
